name: PulseTracker Linter

on: [pull_request, push]

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install 
      run: make install
    - name: Build package
      run: make
    - uses: ricardochaves/python-lint@master
      with:
        python-root-list: 'pulsetracker src'
